pipeline:
  name: basicPipeline
  identifier: basicPipeline
  projectIdentifier: Labs
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: basic
        identifier: basic
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: basicEchoScript
                  identifier: basicEchoScript
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "This is just a basic step"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: Confirmation
        identifier: Confirmation
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Email
                  name: ConfirmationEmail
                  identifier: ConfirmationEmail
                  spec:
                    to: vanshaj.bajaj@harness.io
                    cc: ""
                    subject: Basic Pipeline Success
                    body: |-
                      Hey man!
                      Pipeline is executed successfully!

                      Cheers
                  timeout: 10m
        tags: {}
